### ISSUE TITLE
Feedback on org-id-cleanup.el

### ISSUE THREAD

**Issue by alphapapa** [marcIhm/org-working-set#1]
Hi Marc,

I saw your post on the mailing list asking for feedback.  So here is some.  :)

* https://github.com/marcIhm/org-working-set/blob/1785e3cf4720af94b8a052af93661afa6a3b8add/org-id-cleanup.el#L55
The name of this variable doesn't seem quite right.  What's "extra" about it?  :)
* https://github.com/marcIhm/org-working-set/blob/1785e3cf4720af94b8a052af93661afa6a3b8add/org-id-cleanup.el#L56-L59
These variables probably don't need to be special variables, but instead could be lexically bound in the master function.  Alternatively, if you split up the master function (see later comment), using special variables to track data like this would make more sense.  In that case, you might want to be sure to set them to nil when done to avoid wasting memory.
* https://github.com/marcIhm/org-working-set/blob/1785e3cf4720af94b8a052af93661afa6a3b8add/org-id-cleanup.el#L68
This function is very long.  Each step within it could be its own function, which would make the code easier to follow.
* https://github.com/marcIhm/org-working-set/blob/1785e3cf4720af94b8a052af93661afa6a3b8add/org-id-cleanup.el#L85
What does `buna` mean?
* https://github.com/marcIhm/org-working-set/blob/1785e3cf4720af94b8a052af93661afa6a3b8add/org-id-cleanup.el#L86-L87
This seems a little unidiomatic.  But I haven't tested the code, so maybe I'm wrong.
* https://github.com/marcIhm/org-working-set/blob/1785e3cf4720af94b8a052af93661afa6a3b8add/org-id-cleanup.el#L95
These embedded explanatory strings could go in a variable to make the function easier to read.  You could use an alist with each string having a short, descriptive keyword symbol key.  Alternatively, if each step were its own function, it might be more useful to leave the strings embedded in the functions.
* Also, rather than write the strings on a single line and call `fill-paragraph` sometimes, it would probably be better to write them as filled, multi-line strings to begin with, like regular docstrings in Elisp.  This would make them much easier to read in the code, and you can use `M-q` to fill them.
* https://github.com/marcIhm/org-working-set/blob/1785e3cf4720af94b8a052af93661afa6a3b8add/org-id-cleanup.el#L297-L298 https://github.com/marcIhm/org-working-set/blob/1785e3cf4720af94b8a052af93661afa6a3b8add/org-id-cleanup.el#L316-L317
These docstrings don't say what value the functions return.

**Comment by marcIhm** [comment]
Hi,
2.1.6 does a major refactoring of the control structure, including a split of the steps from the central function into multiple smaller functions. This fixes most issues; checkdoc, elint-buffer and byte-compile are satisfied too :-) BTW: I keep hold on (fill-paragraph) because this works for windows of all sizes ...
Thanx for your input !
